import { Header } from "@/components/Header";
import Footer from "@/components/Footer";
import { Shield, Lock, AlertTriangle, Key, FileCheck, Globe, Eye, ShieldCheck } from "lucide-react";

const Security = () => {
  return (
    <div className="min-h-screen bg-background">
      <Header />
      
      <main>
        {/* Hero Section */}
        <section className="relative overflow-hidden bg-gradient-to-br from-rose-50 via-background to-muted/30 py-20">
          <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="flex items-center gap-4 mb-6">
              <div className="flex-shrink-0 w-20 h-20 rounded-full bg-crimson/10 flex items-center justify-center">
                <Shield className="w-10 h-10 text-crimson" />
              </div>
              <h1 className="text-4xl md:text-5xl font-ubuntu font-bold text-foreground">
                Security & Compliance at MerchantHaus
              </h1>
            </div>
            <p className="text-xl text-muted-foreground leading-relaxed text-justify">
              At MerchantHaus, security isn't just a feature — it's a foundation. We safeguard merchants and their customers through world-class compliance, robust encryption standards, and proactive fraud prevention.
            </p>
          </div>
        </section>

        {/* Main Content */}
        <section className="py-16 bg-background">
          <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 space-y-16">
            
            {/* PCI DSS Compliance */}
            <div className="space-y-6">
              <div className="flex items-start gap-4">
                <div className="flex-shrink-0 w-12 h-12 rounded-lg bg-crimson/10 flex items-center justify-center">
                  <ShieldCheck className="w-6 h-6 text-crimson" />
                </div>
                <div>
                  <h2 className="text-3xl font-ubuntu font-bold text-foreground mb-4">
                    1. PCI DSS Compliance (Level 1)
                  </h2>
                </div>
              </div>
              
              <div className="space-y-4 text-muted-foreground leading-relaxed">
                <p className="text-justify">
                  <strong className="text-foreground">Highest Level Certification:</strong> MerchantHaus operates under the Payment Card Industry Data Security Standard (PCI DSS) at Level 1 – the highest certification available for service providers. This means we meet the strictest requirements for protecting cardholder data, as defined by major card networks. PCI DSS Level 1 compliance involves rigorous annual audits by Qualified Security Assessors and quarterly network scans to validate our security controls.
                </p>
                
                <p className="text-justify">
                  <strong className="text-foreground">Encrypted and Never Stored:</strong> We ensure that cardholder data is never stored in raw form on our systems. All sensitive card data (the Primary Account Number and more) is immediately encrypted or tokenized at capture, so it is never left "in the clear" on disks or databases. By adhering to this principle, MerchantHaus reduces breach risk and limits legal exposure – if data isn't stored, it can't be stolen.
                </p>
                
                <p className="text-justify">
                  <strong className="text-foreground">Secure Processing Environment:</strong> All card transactions are processed through secure, PCI-certified systems. Our payment infrastructure is regularly tested and audited to ensure a secure Cardholder Data Environment. MerchantHaus undergoes annual PCI DSS assessments and maintains continuous compliance rather than treating it as a one-time event.
                </p>
              </div>
            </div>

            {/* Network Tokenization */}
            <div className="space-y-6">
              <div className="flex items-start gap-4">
                <div className="flex-shrink-0 w-12 h-12 rounded-lg bg-crimson/10 flex items-center justify-center">
                  <Key className="w-6 h-6 text-crimson" />
                </div>
                <div>
                  <h2 className="text-3xl font-ubuntu font-bold text-foreground mb-4">
                    2. Network Tokenization & Data Encryption
                  </h2>
                </div>
              </div>
              
              <div className="space-y-4 text-muted-foreground leading-relaxed">
                <p className="text-justify">
                  <strong className="text-foreground">Network Tokenization:</strong> We employ network tokenization to replace actual card numbers with secure tokens issued through the card networks. A customer's 16-digit PAN (Primary Account Number) is swapped out for a random token generated by Visa, Mastercard, or other networks. These network tokens act as stand-ins for the real card, and they are typically domain- or merchant-specific.
                </p>
                
                <p className="text-justify">
                  <strong className="text-foreground">End-to-End Data Encryption:</strong> All transactions on MerchantHaus are protected with strong encryption protocols in transit and at rest. We enforce TLS 1.2+ (and support TLS 1.3) for all communications, using only modern cipher suites that provide Perfect Forward Secrecy. By using robust encryption (AES-256, TLS-ECDHE, etc.), we not only comply with PCI DSS requirements for data in transit but also meet or exceed U.S. federal cybersecurity guidelines.
                </p>
              </div>
            </div>

            {/* Fraud Prevention */}
            <div className="space-y-6">
              <div className="flex items-start gap-4">
                <div className="flex-shrink-0 w-12 h-12 rounded-lg bg-crimson/10 flex items-center justify-center">
                  <Eye className="w-6 h-6 text-crimson" />
                </div>
                <div>
                  <h2 className="text-3xl font-ubuntu font-bold text-foreground mb-4">
                    3. Fraud Prevention & Transaction Monitoring
                  </h2>
                </div>
              </div>
              
              <div className="space-y-4 text-muted-foreground leading-relaxed">
                <p className="text-justify">
                  MerchantHaus uses AI-driven fraud detection and real-time monitoring to catch suspicious activity before it impacts merchants or customers. Our fraud prevention engine continuously analyzes transaction patterns, user behavior, and device data to identify anomalies that could indicate fraud.
                </p>
                
                <div className="bg-muted/50 rounded-lg p-6 my-6">
                  <h3 className="font-ubuntu font-semibold text-foreground mb-4">Key Fraud Prevention Features:</h3>
                  <ul className="space-y-2 text-sm">
                    <li className="flex items-start gap-2">
                      <span className="text-crimson mt-1">•</span>
                      <span><strong>AI/ML Fraud Scoring:</strong> Machine learning models analyze each transaction for suspicious patterns in real time.</span>
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-crimson mt-1">•</span>
                      <span><strong>Velocity & Volume Controls:</strong> Rapid-fire transactions or abnormal spending spikes are flagged or halted.</span>
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-crimson mt-1">•</span>
                      <span><strong>Geo-Velocity & IP Analysis:</strong> Transactions requiring unrealistic travel between locations are identified as likely fraud.</span>
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-crimson mt-1">•</span>
                      <span><strong>Device Fingerprinting:</strong> Recognition of devices and browser environments to detect new or compromised devices.</span>
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-crimson mt-1">•</span>
                      <span><strong>Chargeback Management:</strong> Immediate alerts on disputes and integration with card networks for efficient handling.</span>
                    </li>
                  </ul>
                </div>
              </div>
            </div>

            {/* 3D Secure */}
            <div className="space-y-6">
              <div className="flex items-start gap-4">
                <div className="flex-shrink-0 w-12 h-12 rounded-lg bg-crimson/10 flex items-center justify-center">
                  <Lock className="w-6 h-6 text-crimson" />
                </div>
                <div>
                  <h2 className="text-3xl font-ubuntu font-bold text-foreground mb-4">
                    4. Strong Customer Authentication with 3D Secure 2.0
                  </h2>
                </div>
              </div>
              
              <div className="space-y-4 text-muted-foreground leading-relaxed">
                <p className="text-justify">
                  To further protect online payments and meet international security regulations, MerchantHaus supports Strong Customer Authentication (SCA) via 3D Secure 2.0 (EMV 3DS). During authentication, the customer may be prompted to verify their identity using two factors – something they know, have, or are.
                </p>
                
                <p className="text-justify">
                  <strong className="text-foreground">Security without Sacrificing Convenience:</strong> 3D Secure 2.0 is designed to be frictionless whenever possible. It carries 10 times more data to the issuer than the old 3DS 1.0, allowing intelligent risk-based checks behind the scenes. In many cases, if the transaction is deemed low risk, the customer will not see any prompt at all.
                </p>
              </div>
            </div>

            {/* Data Privacy */}
            <div className="space-y-6">
              <div className="flex items-start gap-4">
                <div className="flex-shrink-0 w-12 h-12 rounded-lg bg-crimson/10 flex items-center justify-center">
                  <FileCheck className="w-6 h-6 text-crimson" />
                </div>
                <div>
                  <h2 className="text-3xl font-ubuntu font-bold text-foreground mb-4">
                    5. Data Privacy & Compliance
                  </h2>
                </div>
              </div>
              
              <div className="space-y-4 text-muted-foreground leading-relaxed">
                <p className="text-justify">
                  MerchantHaus is committed to protecting personal data and respecting privacy rights across all regions. We comply with major data protection laws including the EU's GDPR, California's CCPA (and CPRA), South Africa's POPIA, and other applicable privacy regulations.
                </p>
                
                <div className="grid md:grid-cols-2 gap-6 my-6">
                  <div className="bg-muted/50 rounded-lg p-6">
                    <h3 className="font-ubuntu font-semibold text-foreground mb-3">Data Minimization</h3>
                    <p className="text-sm">We only collect personal data that is necessary for providing our services and fulfilling legal/financial requirements.</p>
                  </div>
                  <div className="bg-muted/50 rounded-lg p-6">
                    <h3 className="font-ubuntu font-semibold text-foreground mb-3">User Rights</h3>
                    <p className="text-sm">Users can access, correct, delete, or port their personal information at any time through their account settings or by contacting us.</p>
                  </div>
                  <div className="bg-muted/50 rounded-lg p-6">
                    <h3 className="font-ubuntu font-semibold text-foreground mb-3">Transparency</h3>
                    <p className="text-sm">We maintain a clear Privacy Policy detailing what data we collect, how we use it, and who we share it with.</p>
                  </div>
                  <div className="bg-muted/50 rounded-lg p-6">
                    <h3 className="font-ubuntu font-semibold text-foreground mb-3">Data Security</h3>
                    <p className="text-sm">All personal data is encrypted, access-controlled, and stored securely with regular security audits.</p>
                  </div>
                </div>
              </div>
            </div>

            {/* Additional Measures */}
            <div className="space-y-6">
              <div className="flex items-start gap-4">
                <div className="flex-shrink-0 w-12 h-12 rounded-lg bg-crimson/10 flex items-center justify-center">
                  <AlertTriangle className="w-6 h-6 text-crimson" />
                </div>
                <div>
                  <h2 className="text-3xl font-ubuntu font-bold text-foreground mb-4">
                    6. Incident Response & Business Continuity
                  </h2>
                </div>
              </div>
              
              <div className="space-y-4 text-muted-foreground leading-relaxed">
                <p className="text-justify">
                  MerchantHaus maintains a comprehensive Incident Response Plan to quickly detect, contain, and remediate security incidents. Our team is trained to respond to breaches, data leaks, or service disruptions with minimal delay. We conduct regular tabletop exercises and simulations to ensure our response procedures are tested and effective.
                </p>
                
                <p className="text-justify">
                  <strong className="text-foreground">Business Continuity:</strong> We have disaster recovery protocols and backup systems in place to ensure service availability even during unexpected events. Our infrastructure is designed for redundancy and failover, minimizing downtime and ensuring that merchants can continue processing payments reliably.
                </p>
              </div>
            </div>

          </div>
        </section>

        {/* CTA Section */}
        <section className="py-16 bg-muted/30">
          <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
            <h2 className="text-3xl font-ubuntu font-bold text-foreground mb-4">
              Questions About Our Security?
            </h2>
            <p className="text-lg text-muted-foreground mb-8">
              Our team is here to discuss how we protect your business and your customers.
            </p>
            <div className="flex flex-wrap justify-center gap-4">
              <a 
                href="tel:15056006042"
                className="inline-flex items-center justify-center rounded-full bg-crimson px-8 py-4 text-base font-semibold text-white shadow-sm transition hover:bg-crimson/90"
              >
                Call 1-505-600-6042
              </a>
              <a 
                href="/apply"
                className="inline-flex items-center justify-center rounded-full border-2 border-crimson px-8 py-4 text-base font-semibold text-crimson transition hover:bg-crimson/10"
              >
                Apply Now
              </a>
            </div>
          </div>
        </section>
      </main>
      
      <Footer />
    </div>
  );
};

export default Security;
