import { Header } from "@/components/Header";
import Footer from "@/components/Footer";
import { useEffect } from "react";
import NavTree from "@/components/NavTree";

/**
 * Two‑Factor Authentication
 *
 * Enabling two‑factor authentication (2FA) adds an extra layer of
 * protection to your account. This guide outlines the benefits of 2FA,
 * shows how to set it up with an authenticator app, explains the login
 * process and provides instructions for recovering access if you lose
 * your device【898554492633279†L51-L80】【898554492633279†L85-L137】.
 */
const TwoFactorAuthentication = () => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);
  return (
    <>
      <Header />
      <main className="bg-background py-16 px-6">
        <div className="max-w-5xl mx-auto flex">
          <NavTree />
          <div className="flex-1">
            <h1 className="text-4xl md:text-5xl font-bold text-foreground mb-4">
              Two‑Factor Authentication
            </h1>
            <p className="text-muted-foreground mb-8 leading-relaxed">
              Two‑factor authentication (2FA) requires you to enter a one‑time
              code in addition to your password. This significantly reduces
              the risk of account compromise and removes the need to change
              your password every 90 days.
            </p>

            {/* Overview */}
            <section id="overview" className="space-y-4 mb-12">
              <h2 className="text-2xl font-semibold text-foreground">Overview</h2>
              <p className="text-muted-foreground leading-relaxed">
                With 2FA, you’ll sign in using your password and a code
                generated by an authenticator app. Once enabled, you can opt
                to trust devices for 30 days, skip password changes and
                bypass device recognition prompts【898554492633279†L51-L80】.
              </p>
            </section>

            {/* Setting Up 2FA */}
            <section id="setting-up" className="space-y-4 mb-12">
              <h2 className="text-2xl font-semibold text-foreground">
                Setting Up 2FA
              </h2>
              <p className="text-muted-foreground leading-relaxed mb-4">
                To enable 2FA:
              </p>
              <ol className="list-decimal pl-6 space-y-2 text-muted-foreground mb-4">
                <li>
                  Download a time‑based one‑time password app such as Google
                  Authenticator or Authy.
                </li>
                <li>
                  Go to the two‑factor settings page and click <em>Enable
                  Two‑Factor</em>【898554492633279†L85-L137】.
                </li>
                <li>
                  Scan the QR code displayed in the portal with your
                  authenticator app.
                </li>
                <li>
                  Enter the six‑digit code generated by the app to confirm
                  setup. After saving, 2FA will be required each time you
                  log in【898554492633279†L85-L137】.
                </li>
              </ol>
            </section>

            {/* Logging In */}
            <section id="logging-in" className="space-y-4 mb-12">
              <h2 className="text-2xl font-semibold text-foreground">Logging In</h2>
              <p className="text-muted-foreground leading-relaxed">
                When 2FA is enabled, enter your username and password as
                usual. You’ll then be prompted for a one‑time code from your
                authenticator app. If you tick “Remember this device,” you
                won’t be asked for a code for 30 days on that device.【898554492633279†L85-L137】
              </p>
            </section>

            {/* Lost Access */}
            <section id="lost-access" className="space-y-4 mb-12">
              <h2 className="text-2xl font-semibold text-foreground">
                Lost Access
              </h2>
              <p className="text-muted-foreground leading-relaxed">
                If you lose your device, contact support to disable 2FA on
                your account. After verifying your identity, support can
                reset 2FA so you can pair a new authenticator. Keep backup
                codes in a secure location to avoid lockout【898554492633279†L85-L137】.
              </p>
            </section>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
};

export default TwoFactorAuthentication;